### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DJKieranl29** [yogurtsyum/qbot#150]
```
TypeError: Cannot read properties of null (reading 'Final')
    at C:\Users\Administrator\Desktop\QBOT\qbot\node_modules\bloxy\dist\client\Client.js:111:43
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\Administrator\Desktop\QBOT\qbot\src\arguments\handleRobloxUser.ts:36:36
```

**Comment by DJKieranl29** [comment]
.
