### ISSUE TITLE
Im getting a really big error in a repl.

### ISSUE THREAD

**Issue by shadowmickey20** [yogurtsyum/qbot#39]
Error: Cannot find module './BaseGuildEmoji'
Require stack:
- /home/runner/AlertTalkativeAnalyst/node_modules/discord.js/src/structures/GuildEmoji.js
- /home/runner/AlertTalkativeAnalyst/node_modules/discord.js/src/managers/GuildEmojiManager.js
- /home/runner/AlertTalkativeAnalyst/node_modules/discord.js/src/client/Client.js
- /home/runner/AlertTalkativeAnalyst/node_modules/discord.js/src/index.js
- /home/runner/AlertTalkativeAnalyst/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/AlertTalkativeAnalyst/node_modules/discord.js/src/structures/GuildEmoji.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)Hint: hit control+c anytime to enter REPL.


**Comment by yogurtsyum** [comment]
We need to see some code to help.

**Comment by yogurtsyum** [comment]
Is this solved? This also doesn't seem like a qbot issue.

**Comment by shadowmickey20** [comment]
Just close it, I've fixed it 😊

**Comment by IeuanGol** [comment]
You should see a close button if you login to GitHub

**Comment by shadowmickey20** [comment]
Thanks for the support! I have very thankfull
