### ISSUE TITLE
Getroles command help

### ISSUE THREAD

**Issue by emergingdarkness** [yogurtsyum/qbot#59]
const Discord = require('discord.js');
const roblox = require("noblox.js");
exports.run = async (client, message, args) => {

  const foundId = roblox.getIdFromUsername(message.guild.member.displayName)
  const groupRank = roblox.getRankNameInGroup(7745739, foundId)

   message.member.roles.add(message.guild.roles.cache.find(role => role.name === groupRank)); // Add the users role

const e = new Discord.MessageEmbed()
.setColor('BLUE')
.setTitle(`Prompt Concluded`)
.addField("Added Roles", `${groupRank}`)
.setFooter("Action: Getroles")
message.channel.send(e)
}

**Comment by emergingdarkness** [comment]
Error is (node:97) UnhandledPromiseRejectionWarning: Error: Required argument "username" is missing
    at Object.getIdFromUsername (/home/runner/TAS-Assistant/node_modules/noblox.js/lib/internal/wrap.js:69:19)
    at Object.exports.run (/home/runner/TAS-Assistant/commands/role.js:4:26)
    at Client.<anonymous> (/home/runner/TAS-Assistant/index.js:108:31)
    at Client.emit (events.js:315:20)
    at Client.EventEmitter.emit (domain.js:483:12)
    at MessageCreateAction.handle (/home/runner/TAS-Assistant/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/TAS-Assistant/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/TAS-Assistant/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/TAS-Assistant/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/TAS-Assistant/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/TAS-Assistant/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.EventEmitter.emit (domain.js:483:12)
    at Receiver.receiverOnMessage (/home/runner/TAS-Assistant/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.EventEmitter.emit (domain.js:483:12)
    at Receiver.dataMessage (/home/runner/TAS-Assistant/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/home/runner/TAS-Assistant/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/runner/TAS-Assistant/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/runner/TAS-Assistant/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
(node:97) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:97) UnhandledPromiseRejectionWarning: Error: Required argument "username" is missing
    at Object.getIdFromUsername (/home/runner/TAS-Assistant/node_modules/noblox.js/lib/internal/wrap.js:69:19)
    at Object.exports.run (/home/runner/TAS-Assistant/commands/role.js:4:26)
    at Client.<anonymous> (/home/runner/TAS-Assistant/index.js:108:31)
    at Client.emit (events.js:315:20)
    at Client.EventEmitter.emit (domain.js:483:12)
    at MessageCreateAction.handle (/home/runner/TAS-Assistant/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/TAS-Assistant/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/TAS-Assistant/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/TAS-Assistant/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/TAS-Assistant/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/TAS-Assistant/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.EventEmitter.emit (domain.js:483:12)
    at Receiver.receiverOnMessage (/home/runner/TAS-Assistant/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.EventEmitter.emit (domain.js:483:12)
    at Receiver.dataMessage (/home/runner/TAS-Assistant/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/home/runner/TAS-Assistant/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/runner/TAS-Assistant/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/runner/TAS-Assistant/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
(node:97) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by emergingdarkness** [comment]
![image](https://user-images.githubusercontent.com/68578388/93726453-00b29f00-fb6b-11ea-9799-794a370714bb.png)

**Comment by emergingdarkness** [comment]
Hello?

**Comment by IeuanGol** [comment]
Hi! Since this is not an error relating to qBot we aren't providing support for it (we will when we open our discord server again).

**Comment by emergingdarkness** [comment]
Whens that its been locked for a few weeks

**Comment by emergingdarkness** [comment]
K

**Comment by IeuanGol** [comment]
[This](https://discord.com/invite/code) server might be able to help.

**Comment by TypicallyShad** [comment]
Server now unlocked - there is a qbot plugin for that too which I made.

**Comment by emergingdarkness** [comment]
Where? @TypicallyShad

**Comment by IeuanGol** [comment]
https://discord.gg/976dpbB

**Comment by jplewsy06** [comment]
@TypicallyShad Where is the plug-in you made? Cannot find it.

**Comment by IeuanGol** [comment]
We have a #plugins channel in our [server](https://discord.gg/976dpbB).

**Comment by IeuanGol** [comment]
https://github.com/yogurtsyum/qbot-plugins/blob/master/directory.md

**Comment by jplewsy06** [comment]
There is no getroles plugin whatsoever. 

Have you misread? There’s getinfo but not getroles. @TypicallyShad

**Comment by emergingdarkness** [comment]
> Server now unlocked - there is a qbot plugin for that too which I made.

Theres no get roles plugin..

**Comment by jplewsy06** [comment]
> Theres no get roles plugin..

Indeed.

**Comment by K00L1000** [comment]
No getroles in #plugins

**Comment by yogurtsyum** [comment]
If you need any more help, please ask in the support server.

**Comment by emergingdarkness** [comment]
Ok
